server:
  port: 8001
spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: changgou_goods_route
#          uri: http://localhost:18081
          uri: lb://goods
          predicates:
#          - Host=cloud.itheima.com**
          - Path=/api/goods/**
          filters:
#请求路径中第一个请求路径去掉
          - StripPrefix=2
#          name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
#          args:
#            key-resolver: "#{@ipKeyResolver}"
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 1
        - id: changgou_user_route
          uri: lb://user
          predicates:
          - Path=/api/user/**
          filters:
          - StripPrefix=2
  redis:
    host: 192.168.93.101
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true